name = "skillz-api"
main = "src/index.ts"
compatibility_date = "2024-11-18"
workers_dev = true

[route]
custom_domain = true
pattern = "api.skillz.lat"
zone_name = "skillz.lat"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "skillz-registry"
database_id = "1a3b4fcf-c920-400e-97fb-9b060c3dd6f4"
migrations_dir = "../../packages/db/migrations"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "skillz-packages"

# [[vectorize]]
# binding = "VECTORIZE"
# index_name = "skillz-embeddings"

# [ai]
# binding = "AI"

[vars]
ENVIRONMENT = "production"
BETTER_AUTH_URL = "https://api.skillz.lat"
