name: Lint

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: true

jobs:
  lint-go:
    name: Lint Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Run golangci-lint
        run: |
          cd cli
          golangci-lint run

  lint-node:
    name: Lint Node Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Install Dependencies
        run: |
          cd server
          pnpm install

      - name: Type Check
        run: |
          cd server
          pnpm run typecheck

      - name: Lint
        run: |
          cd server
          pnpm run lint

      - name: Test Server
        run: |
          cd server
          if npm run | grep -q "test"; then
            pnpm run test
          else
            echo "No test script found for server"
          fi
