name: "Release"

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: true

jobs:
  binary:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Build the executable
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          cd cli
          go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o ../skillz-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/skillz

      - name: Rename the executable (Windows)
        if: ${{ matrix.goos == 'windows' }}
        run: mv skillz-${{ matrix.goos }}-${{ matrix.goarch }} skillz-${{ matrix.goos }}-${{ matrix.goarch }}.exe

      - name: Generate Checksums
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          sha256sum skillz-* > SHA256SUMS

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            skillz-${{ matrix.goos }}-${{ matrix.goarch }}
            skillz-${{ matrix.goos }}-${{ matrix.goarch }}.exe
            SHA256SUMS
